src/Entity/ListTodo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ListTodoRepository")
 */
class ListTodo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $todo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getTodo(): ?string
    {
        return $this->todo;
    }

    public function setTodo(string $todo): self
    {
        $this->todo = $todo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/home/home.html.twig
{# templates/home/home.html.twig #}
{%  extends 'base.html.twig' %}
{% block title %}ToDOiT{% endblock %}

{% block main %}
    <main>
        {% if app.user %}
            <ul class="items">

                {% for tasks in list  %}
                    {% if tasks.idUser == app.user.id %}

                    <li>{{ tasks.todo }} <span class="close"><form method="post" action="{{ path('delete', {id: tasks.id}) }}">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tasks.id) }}">
                            <button style="border: none; background: none">&times;</button>
                        </form></span></li>
                    {% endif %}
                {%  endfor %}

            </ul>

            <div id="newItemForm">
                {{ form_start(form) }}
                <div>
                    {{ form_widget(form.todo, {'attr': {'placeholder': 'Créer une note...'}, 'value': '' }) }}
                <input type="image" src="{{ asset('images/Button.png') }}" alt="Add" />
                </div>
                {{ form_end(form) }}
            </div>

        {% else %}
            <ul class="items">
                <li>Aller à la salle <span class="close">&times;</span></li>
                <li class="checked">Payer les factures <span class="close">&times;</span></li>
                <li>Rencontrer George <span class="close">&times;</span></li>
                <li>Acheter des oeufs <span class="close">&times;</span></li>
                <li>Lire un livre <span class="close">&times;</span></li>
            </ul>

            <form id="newItemForm">
                <input class="txtNewItem" type="text" placeholder="Créer une note..." />
                <input type="image" src="{{ asset('images/Button.png') }}" alt="Add" />
            </form>

        {% endif %}

    </main>

{% endblock %}